name: Build and deploy GitHub Pages

on: 
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node Modules
        run: |
          npm ci
      
      #- name: Install Zig
      #  uses: mlugg/setup-zig@v1
      #  with:
      #    version: 0.16.0
      
      # Will re-enable after emulator code
      # somewhat works.
      #- name: Build Zig
      #  run:
      #    zig build -Doptimize=ReleaseSmall
      
      - name: Copy to target
        run: |
          set -euo pipefail

          mv -v target target.bak || true

          echo "Creating target directory..."
          mkdir -pv target
          mkdir -pv target/assets
          mkdir -p target/thirdparty

          echo "Copying files...."
          cp -rv source/website/. target/
          cp -rv assets/. target/assets/
          cp -r node_modules/@xterm/. target/thirdparty

          echo "Final target structure:"
          ls -lah target/

      - name: Upload target
        uses: actions/upload-pages-artifact@v3
        with:
          path: target

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4